blank_issues_enabled: true
contact_links:
  - name: ðŸ‘¥ Discussions
    url:  https://github.com/wulfland/AccelerateDevOps/discussions/new
    about: Please use discussions for issues that are not a bug, enhancement or feature request
