name: Deploy-GKE

on: [workflow_dispatch]

env:
  PROJECT_ID: ${{ secrets.GKE_PROJECT }}
  GKE_CLUSTER: xyz-demo-cluster
  GKE_LOCATION: europe-west3-a
  GKE_REGION: europe-west3
  DEPLOYMENT_NAME: xyz-demo-shop-deployment
  IMAGE: xyz-demo-shop

jobs:
  setup-build-publish-deploy:
    name: Setup, Build, Publish, and Deploy
    runs-on: ubuntu-latest
    environment: prod

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    # Setup gcloud CLI
    - uses: google-github-actions/setup-gcloud@v0.2.0
      with:
        service_account_key: ${{ secrets.GKE_SA_KEY }}
        project_id: ${{ secrets.GKE_PROJECT }}
        export_default_credentials: true 

    # Build the Docker image
    - name: Build
      working-directory: ch9_release/src/Tailwind.Traders.Web
      run: |-  
        docker build \
          --tag "$GKE_REGION-docker.pkg.dev/$PROJECT_ID/$PROJECT_ID/$IMAGE:$GITHUB_SHA" \
          --build-arg GITHUB_SHA="$GITHUB_SHA" \
          --build-arg GITHUB_REF="$GITHUB_REF" \
          .

    # Push the Docker image to Google Container Registry
    - name: Publish
      run: |-
        gcloud auth configure-docker $GKE_REGION-docker.pkg.dev --quiet
        docker push "$GKE_REGION-docker.pkg.dev/$PROJECT_ID/$PROJECT_ID/$IMAGE:$GITHUB_SHA"

    # Get the GKE credentials so we can deploy to the cluster
    - uses: google-github-actions/get-gke-credentials@v0.2.1
      with:
        cluster_name: ${{ env.GKE_CLUSTER }}
        location: ${{ env.GKE_LOCATION }}
        credentials: ${{ secrets.GKE_SA_KEY }}

    # Set up kustomize
    - name: Set up Kustomize
      working-directory: ch9_release/src/Tailwind.Traders.Web
      run: |-
        curl -sfLo kustomize https://github.com/kubernetes-sigs/kustomize/releases/download/v3.1.0/kustomize_3.1.0_linux_amd64
        chmod u+x ./kustomize

    # Deploy the Docker image to the GKE cluster
    - name: Deploy
      working-directory: ch9_release/src/Tailwind.Traders.Web
      run: |-
        # ./kustomize edit set image gcr.io/PROJECT_ID/IMAGE:TAG=gcr.io/$PROJECT_ID/$IMAGE:$GITHUB_SHA
        # ./kustomize build . | kubectl apply -f -
        # kubectl rollout status deployment/$DEPLOYMENT_NAME
        # kubectl get services -o wide
        kubectl create deployment $DEPLOYMENT_NAME --image=$GKE_REGION-docker.pkg.dev/$PROJECT_ID/$PROJECT_ID/$IMAGE:$GITHUB_SHA
        kubectl scale deployment $DEPLOYMENT_NAME --replicas=3
        kubectl autoscale deployment $DEPLOYMENT_NAME --cpu-percent=80 --min=1 --max=5
        kubectl expose deployment $DEPLOYMENT_NAME --name=$DEPLOYMENT_NAME --type=LoadBalancer --port 80 --target-port 80
        kubectl get services -o wide


