name: PR-Validation

on: [pull_request]

jobs:
  Build:
    runs-on: ubuntu-latest

    steps:
    - name: 'Checkout Github Action'
      uses: actions/checkout@v3

    - name: Set up .NET Core
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: '5.0.x'

    - name: Setup Node
      uses: actions/setup-node@v2.5.1
      with:
        node-version: 10.16.3    

    - name: Install dependencies in client app
      working-directory: ch9_release/src/Tailwind.Traders.Web/ClientApp
      run: npm install

    - name: Build and publish with dotnet
      working-directory: ch9_release/src/Tailwind.Traders.Web
      run: |
        dotnet build --configuration Release
